model_fa2_en = {'آسترا سدان': 'astra sedan', 'آسترا هاچ بک': 'astra hatchback', 'کورسا': 'corsa', 'موکا': 'mokka',
                'وکترا': 'vectra', 'فور 4': 'forfour', 'کاتلاس سیرا': 'ciera', 'کاتلاس کوپه': 'cutlass', '3': '3',
                '350': '350', '360': '360', '550': '550', '6': '6', 'GS': 'gs', 'GT': 'gt', 'RX5': 'rx5', '110': '110',
                '110S': '110s', '315 صندوق دار': '315 sedan', '315هاچ بک': '315 hatchback', '530': '530', 'X22': 'x22',
                'X33': 'x33', 'X33 S': 'x33s', 'x55': 'x55', 'دی مکس': 'd max', 'وانت': 'pickup', 'Q70': 'q70',
                '4C': '4c', 'جولیتا': 'giulietta', 'میتو': 'mito', ' دو کابین آسنا': 'asna 4door', 'A6': 'a6',
                'A8': 'a8', 'Q5': 'q5', 'S6': 's6', 'TT کوپه': 'tt coupe', 'X1': 'x1', 'X3': 'x3', 'X4': 'x4',
                'X5': 'x5', 'X6': 'x6', 'Z4': 'z4', 'سری 1 کروک': '1 series convertible',
                'سری 1 کوپه': '1 series coupe', 'سری 1 هاچ بک': '1 series', 'سری 2 اکتیوتورر': '2 series activetourer',
                'سری 2 کروک': '2 series convertible', 'سری 2 کوپه': '2 series coupe', 'سری 3 GT': '3 series gt',
                'سری 3 سدان': '3 series sedan', 'سری 3 کروک': '3 series convertible', 'سری 3 کوپه': '3 series coupe',
                'سری 4 کروک': '4 series convertible', 'سری 4 کوپه': '4 series coupe',
                'سری 4 گرن کوپه': '4 series grancoupe', 'سری 5 سدان': '5 series sedan',
                'سری 6 کروک': '6 series convertible', 'سری 6 کوپه': '6 series coupe',
                'سری 6 گرن کوپه': '6 series grancoupe', 'سری 7': '7 series', 'سری i': 'i series', 'کلاسیک': 'classic',
                'X25': 'x25', 'سابرینا هاچ بک (مونتاژ)': 'sabrina hatchback ir', 'سنوا': 'senova', 'H220': 'h220',
                'H230': 'h230', 'H2L': 'h2l', 'H320': 'h320', 'H330': 'h330', 'V5': 'v5', 'کراس': 'cross C3',
                'B30': 'b30', 'B50': 'b50', 'B50F': 'b50f', 'کنتینانتال GT': 'continental gt', 'کلاس A': 'a class',
                'کلاس B': 'b class', 'کلاس C': 'c class', 'کلاس C کوپه': 'c class coupe', 'کلاس CLA': 'cla class',
                'کلاس CLK کوپه': 'clk class coupe', 'کلاس CLS': 'cls class', 'کلاس E': 'e class',
                'کلاس E (مونتاژ)': 'e class ir', 'کلاس E کروک': 'e class convertible', 'کلاس E کوپه': 'e class coupe',
                'کلاس G': 'g class', 'کلاس GL': 'gl class', 'کلاس GLA': 'gla class', 'کلاس GLK': 'glk class',
                'کلاس ML': 'ml class', 'کلاس S': 's class', 'کلاس SE': 'se class', 'کلاس SL': 'sl class',
                'کلاس SLC': 'slc class', 'کلاس SLK': 'slk class', 'کلاس SLS': 'sls class', 'ون': 'van', 'BX5': 'bx5',
                'BX7': 'bx7', 'F3': 'f3', 'T3': 't3', 'T5': 't5', 'B3 (مونتاژ)': 'b3 ir', 'سنچری': 'century',
                'چهار در': '4doors', 'دو در': '2doors', 'وانت دو کابین': 'pickup2cab', 'هرور': 'herour', '111': '111',
                '131': '131', '132': '132', '141': '141', '151': '151', 'صندوق دار': 'sedan', 'هاچ بک': 'hatchback',
                'جن تو': 'gen2', 'ویرا': 'wira', '2008': '2008', '206': '206 ir', '206 SD': '206sd', '207': '207',
                '207 صندوقدار': '207sd', '301': '301', '405': '405', '405 استیشن': '405 station', '407': '407',
                '504': '504', '508': '508', 'RD': 'rd', 'RDI': 'rdi', 'پارس': 'pars', 'روآ': 'roa', '911': '911',
                'باکستر': 'boxster', 'پانامرا': 'panamera', 'کاین': 'cayenne', 'کیمن S': 'cayman s', 'ماکان': 'macan',
                'سدان': 'sedan', '86 GT': 'gt86', 'C-HR': 'c hr', 'C-HR هیبرید': 'c hr hybrid', 'اریون': 'aurion',
                'اف جی کروز': 'fj cruiser', 'پرادو  چهار در': 'prado 4doors', 'پرادو دو در': 'prado 2doors',
                'پریوس': 'prius', 'پریویا': 'previa', 'راوفور': 'rav4', 'سکویا': 'sequoia', 'سولارا': 'solara',
                'فرچونر': 'furtuner', 'کارینا': 'carina', 'کراون': 'crown', 'کرولا': 'corolla', 'کرونا': 'corona',
                'کریسیدا': 'cressida', 'کمری': 'camry', 'کمری هیبرید': 'camry hybrid',
                'لندکروز چهار در': 'landcruiser 4door', 'لندکروز دو در': 'landcruiser 2door',
                'لندکروز وانت تک کابین': 'landcruiser pickup 2door',
                'لندکروز وانت دو کابین': 'landcruiser pickup 4door', 'هایس': 'hiace', 'هایلوکس دو کابین': 'hilux 4door',
                'هایلوکس دو کابین بلند': 'hilux high', 'یاریس صندوق دار': 'yaris', 'یاریس هاچ بک': 'yaris hatchback',
                'S3': 's3', 'S5': 's5', 'جی 3 سدان': 'j3 sedan', 'جی 3 هاچ بک': 'j3 hatchback', 'جی 4': 'j4',
                'جی 5': 'j5', 'E PACE': 'e pace', 'XJ': 'xj', 'گوناگون': 'misc', 'وندورا': 'vendura', 'آهو': 'ahoo',
                'آهو وانت': 'ahoo pickup', 'توسن': 'tosan', 'چروکی': 'cherokee', 'رنگلر': 'wrangler',
                'رنه گید': 'renegade', 'شهباز': 'shahbaz', 'صحرا': 'sahra', 'GC6': 'gc6', 'امگرند 7': 'emgrand7',
                'امگرند RV-7': 'emgrand7 rv', 'امگرند X7': 'emgrand x7', 'CS 35': 'cs35', 'CS 35 (مونتاژ)': 'cs35 ir',
                'ایدو': 'eado', 'آریزو 5': 'arrizo5', 'آریزو 5TE': 'arrizo5te', 'آریزو 6': 'arrizo6',
                'تیگو 5': 'tiggo5', 'تیگو 7': 'tiggo7', 'X7': 'x7', 'H30 کراس': 'h30 cross', 'پلاس': 'plus',
                'معمولی': '1.7', 'رم چارجر (وانت)': 'ramcharger pickup', 'اسپرو': 'espero', 'ریسر': 'racer',
                'سیلو': 'cielo', 'ماتیز': 'matiz', '5': '5', '5LS': '5ls', '7 کراس بک': 'crossback 7', 'EL': 'el',
                'LX': 'lx', 'اسکالا': 'scala', 'پارس تندر': 'pars tondar', 'پی کی': 'pk', 'تالیسمان': 'talisman',
                'تندر وانت': 'tundar pickup', 'تندر90': 'tondar90', 'داستر': 'duster', 'ساندرو': 'sandero',
                'ساندرو استپ وی': 'sandero stepway', 'سپند': 'sepand', 'سفران': 'safrane', 'سیمبل': 'symbol',
                'فلوئنس': 'fluence', 'کپچر': 'captur', 'کولیوس': 'koleos', 'لاگونا کوپه': 'laguna coupe',
                'لتیتود': 'latitude', 'مگان (مونتاژ)': 'megan ir', 'مگان (وارداتی)': 'megan', 'کوپا': 'coupa',
                'آریو': 'Ario', 'اکتیون': 'actyon', 'تیوولی': 'tivoli', 'چیرمن': 'chairman', 'رکستون': 'rexton',
                'کایرون': 'kyron', 'موسو': 'musso', 'نیو اکتیون': 'new actyon', 'نیو کوراندو': 'new korando',
                'EX دنده ای': 'ex mt', 'SX دنده ای': 'sx mt', 'اتوماتیک': 'at', 'SE': 'se', 'سریر': 'sarir',
                'سورن': 'soren', 'کیزاشی': 'kizashi', 'گراند ویتارا (مونتاژ)': 'grand vitara ir',
                'گراند ویتارا (وارداتی)': 'grand vitara', 'C3 (مونتاژ)': 'c3 ir', 'C5': 'c5', 'دی اس 21': 'ds 21',
                'زانتیا': 'xantia', 'ژیان': 'jian', 'II': 'II', 'لئون': 'leon', 'اپترا': 'optra', 'ایمپالا': 'impala',
                'سابربن': 'suburban', 'کاپریس': 'caprice', 'کامارو': 'camaro', 'مونت کارلو': 'montecarlo',
                'نوا': 'nova', 'نوا(مونتاژ)': 'nova ir', 'تونلند': 'tunland', 'ساوانا': 'sauvana',
                'ساوانا (مونتاژ)': 'sauvana ir', 'اج': 'edge', 'تاروس': 'taurus', 'ترانزیت': 'transit',
                'T2-Kombi': 't2 kombi', 'بیتل': 'beetle', 'بیتل کروک': 'beetle convertible', 'پاسات': 'passat',
                'ترنسپورتر': 'transporter', 'تیگوان': 'tiguan', 'کدی': 'caddy', 'گل': 'gol', 'گلف': 'golf',
                'مولتی ون': 'multivan', '500': '500', 'سی ینا': 'siena', '2': '2 ir', 'تک کابین': '2door',
                'دو کابین': '4door', 'سویل': 'seville', 'سویل(مونتاژ)': 'seville ir', '300C': '300c',
                'اتوماتیک فول': 'at full', 'اتوماتیک فول پلاس': 'at full plus', 'دنده ای': 'manual',
                'دنده ای R': 'manual r', 'اپتیما': 'optima', 'اپتیما هیبرید': 'optima hybrid', 'اپیروس': 'opirus',
                'اسپورتیج': 'sportage', 'پیکانتو': 'picanto', 'ریو (مونتاژ)': 'rio ir', 'ریو سدان': 'rio sedan',
                'ریو هاچ بک': 'rio hatchback', 'سراتو': 'cerato', 'سراتو (مونتاژ)': 'cerato ir',
                'سراتو کوپ': 'cerato koup', 'سورنتو': 'sorento', 'کادنزا': 'cadenza', 'کارناوال': 'carnival',
                'کارنز': 'carens', 'موهاوی': 'mohave', 'C30': 'c30', 'وینگل 3': 'wingle 3',
                'وینگل 5 دو کابین': 'wingle 5', 'هاوال M4 (مونتاژ)': 'haval m4 ir', 'ترامپچی GA3S': 'trumpchi ga3s',
                'ترامپچی GS5': 'trumpchi gs5', 'گونو G5': 'g5', 'دسیس': 'thesis', 'CT': 'ct', 'ES': 'es', 'IS': 'is',
                'IS کروک': 'is convertible', 'LS': 'ls', 'NX': 'nx', 'NX هیبرید': 'nx hybrid', 'RX': 'rx',
                'رنجرور': 'rangerover', 'رنجرور اسپرت': 'rangerover sport', 'رنجرور ایووک': 'rangerover evoque',
                'لندرور سری (مونتاژ)': 'series ir', 'V7': 'v7', 'الیزه': 'elise', '520': '520', '620': '620',
                '820': '820', 'X50': 'x50', 'X60': 'x60', 'کواتروپورته': 'quattroporte', 'گرن توریسمو': 'granturismo',
                'گرن کبریو': 'grancabrio', 'گیبلی': 'ghibli', '3 (مونتاژ)': '3 ir',
                '3 جدید صندوق دار (مونتاژ)': '3 sedan', '3 جدید هاچ بک (مونتاژ)': '3 hatchback', '323': '323',
                '929': '929', 'وانت تک\u200cکابین': 'pickup 2door ir', 'وانت دوکابين': 'Pickup 4door ir', 'ASX': 'asx',
                'اوتلندر': 'outlander', 'اوتلندر PHEV': 'outlander phev', 'پاجرو چهار در': 'pajero 4door',
                'پاجرو دو در': 'pajero 2door', 'پاجرو(مونتاژ)': 'pajero ir', 'گالانت': 'galant', 'لنسر': 'lancer',
                'میراژ': 'mirage', 'کانتری من ': 'countryman', 'کلاب من': 'clubman', 'کوپر': 'cooper',
                'ایکس تریل': 'x trail', 'پاترول (وارداتی)': 'patrol im', 'پاترول چهار در': 'patrol 4door ir',
                'پاترول دو در': 'patrol 2door ir', 'پیکاپ تک کابین': 'pickup ir 1cab',
                'پیکاپ دو کابین': 'pickup ir 2cab', 'تی ینا': 'teana ir', 'تی ینا (وارداتی)': 'teana im',
                'جوک': 'juke', 'رونیز': 'roniz', 'سرانزا': 'seranza', 'سنترا': 'sentra', 'قشقایی': 'qashqai',
                'ماکسیما': 'maxima ir', 'ماکسیما (وارداتی)': 'maxima im', 'مورانو': 'murano',
                'وانت زامیاد': 'zamyad pickup', 'آریسان': 'arisan', 'پادرا': 'padra', 'داتسون': 'datsun',
                'دییر': 'deer', 'ریچ': 'rich', 'کارا (تک کابین)': 'cara 2door', 'کارا (دو کابین)': 'cara 4door',
                'کارو تک کابین': 'caro 2door', 'کارو دو کابین': 'caro 4door', '244': '244',
                'C70 کروک': 'c70 convertible', 'V40': 'v40', 'XC60': 'xc60', 'XC90': 'xc90', 'دلیکا': 'delica',
                'کاروان سایپا': 'caravan saipa', 'نارون': 'narvan', 'وانا': 'vana', 'H2': 'h2', 'S7': 's7',
                'X5 (مونتاژ)': 'x5 ir', 'X7 (مونتاژ)': 'x7 ir', 'CR-V': 'cr v', 'آکورد': 'accord', 'سیویک': 'civic',
                'لجند': 'legend', 'T205': 't205', 'H 350': 'h 350', 'i10 (مونتاژ)': 'i10 ir', 'i20': 'i20',
                'i20 (مونتاژ)': 'i20 ir', 'i30': 'i30', 'i40': 'i40', 'i40 استیشن': 'i40 sw', 'استارکس': 'starex',
                'اکسل': 'excel', 'اکسنت': 'accent', 'اکسنت (مونتاژ)': 'accent ir', 'النترا': 'elantra',
                'النترا (مونتاژ)': 'elantra ir', 'آزرا (گرنجور)': 'azera', 'آوانته': 'avante', 'تراجت': 'trajet',
                'توسان (ix35)': 'tucson ix35', 'جنسیس': 'genesis', 'جنسیس کوپه': 'genesis coupe',
                'سانتافه (ix45)': 'santafe ix45', 'سنتنیال': 'centennial', 'سوناتا': 'sonata',
                'سوناتا هیبرید': 'sonata hybrid', 'کوپه': 'coupe', 'وراکروز (ix55)': 'veracruz ix55', 'ورنا': 'verna',
                'ولستر': 'veloster'}
brand_fa2_en = {'اپل': 'opel', 'اسمارت': 'smart', 'الدزمبیل': 'oldsmobile', 'ام جی': 'mg', 'ام وی ام': 'mvm',
                'ایسوزو': 'isuzu', 'اینفینیتی': 'infiniti', 'آلفارومئو': 'alfa-romeo', 'آمیکو': 'amico',
                'آئودی': 'audi', 'ب ام و': 'bmw', 'بایک': 'baic', 'برلیانس': 'brilliance', 'بسترن': 'besturn',
                'بنتلی': 'bentley', 'بنز': 'mercedes-benz', 'بورگوارد': 'borgward', 'بی وای دی': 'byd', 'بیسو': 'bisu',
                'بیوک': 'buick', 'پاژن': 'pazhan', 'پراید': 'pride', 'پروتون': 'proton', 'پژو': 'peugeot',
                'پورشه': 'porsche', 'پیکان': 'peykan', 'تویوتا': 'toyota', 'تیبا': 'tiba', 'جک': 'jac',
                'جگوار': 'jaguar', 'جی ام سی': 'gmc', 'جیپ': 'jeep', 'جیلی': 'geely', 'چانگان': 'changan',
                'چری': 'chery', 'دامای': 'domy', 'دانگ فنگ': 'dongfeng', 'دنا': 'dena', 'دوج': 'dodge', 'دوو': 'daewoo',
                'دی اس': 'ds', 'رانا': 'runna', 'راین': 'rayen', 'رنو': 'renault', 'ریگان': 'rigan', 'زوتی': 'zotye',
                'سانگ یانگ': 'ssang-yong', 'ساینا': 'saina', 'سمند': 'samand', 'سوزوکی': 'suzuki', 'سیتروئن': 'citroen',
                'سیمرغ': 'seemorgh', 'سیناد': 'sinad', 'سئات': 'seat', 'شورولت': 'chevrolet', 'فوتون': 'foton',
                'فورد': 'ford', 'فولکس': 'volkswagen', 'فیات': 'fiat', 'کاپرا': 'capra', 'کادیلاک': 'cadillac',
                'کرایسلر': 'chrysler', 'کوییک': 'quick', 'کیا': 'kia', 'گریت وال': 'great-wall', 'گک': 'gac-gonow',
                'لانچیا': 'lancia', 'لکسوس': 'lexus', 'لندرور': 'land-rover', 'لندمارک': 'landmark', 'لوتوس': 'lotus',
                'لیفان': 'lifan', 'مازراتی': 'maserati', 'مزدا': 'mazda', 'میتسوبیشی': 'mitsubishi', 'مینی': 'mini',
                'نیسان': 'nissan', 'وانت': 'pick-up', 'ولوو': 'volvo', 'ون': 'van', 'هامر': 'hummer', 'هاوال': 'haval',
                'هایما': 'haima', 'هن تنگ': 'hanteng', 'هوندا': 'honda', 'هیوسو': 'hyosow', 'هیوندای': 'hyundai'}


def get_brand_fa_2_en():
    return brand_fa2_en


def get_model_fa_2_en():
    return model_fa2_en
